CREATE TABLE Notifications (
  Id INT IDENTITY PRIMARY KEY,
  ToId NVARCHAR(450) NOT NULL,
  FromId NVARCHAR(450) NOT NULL,
  ToName NVARCHAR(250) NOT NULL,
  FromName NVARCHAR(250) NOT NULL,
  IsRead BIT NOT NULL,
  Message NVARCHAR(MAX) NOT NULL
);